name: "MTproto Collector"

on:
  workflow_dispatch:
  schedule:
  - cron: '*/59 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php main.php
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git config credential.helper store
          git add -A
          git commit -m "🚀 Proxies Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
